pipeline {
    agent any
    /* parameters {
    string(name: 'BRANCH', defaultValue: 'master', description: 'Branch to build')
    choise(name: 'ENVIRONMENT', choices: ['DEV', 'QA', 'PROD'], description: 'Environment to deploy')
    choise(name: 'VERSION', choices:['1.1.0', '1.2.0','1.3.0'], description: 'Version to deploy')
    booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Deploy to environment')
    booleanParam(name: 'EXECUTE_TESTS', defaultValue: false, description: 'Excute tests')
    }*/
    environment {
        Git_Token = credentials('gitToken')
        Dashboard_Repo = 'https://github.com/EasyWay07/dashboardParking.git'
        Mobile_Client_Repo = 'https://github.com/EasyWay07/EasyParkClient.git'
        Mobile_Gardien_Repo = 'https://github.com/EasyWay07/EasyParkGardien.git'
        APi_Repo = 'https://github.com/EasyWay07/EasyParkBackEnd.git'
        Docker_Token = credentials('dockerToken')
    }
    /*triggers {
        pollSCM 'H/5 * * * *'
    }*/
    stages {
        stage('Pull') {
            steps{
                script{
                    echo "Pulling from Github"
                    checkout([$class: 'GitSCM', branches: [[name: '*/main']],
                        userRemoteConfigs: [[
                            credentialsId: Git_Token,
                            url: Dashboard_Repo
                        ]]
                    ])
                }
            } 
        }
        stage('Build') {
            steps {
                script {
                    echo "Building..."
                    bat "cd ParkingDashboard && npm install --legacy-peer-deps && npm run build"
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    echo "Testing..."
                    bat "cd ParkingDashboard && npm run test"
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker Image..."
                    bat "cd ParkingDashboard && docker build -t dashboardparking ."
                }
            }
        }
        stage('Deploy to Docker Hub') {
            steps {
                script {
                    echo "Deploying..."
                    bat "cd ParkingDashboard && docker logout"
                    bat "cd ParkingDashboard && docker login --username $Docker_Token_USR --password $Docker_Token_PSW"
                    echo "Login on"
                    bat "cd ParkingDashboard && docker tag dashboardparking $Docker_Token_USR/dashboardparking:latest"
                    bat "cd ParkingDashboard && docker push $Docker_Token_USR/dashboardparking:latest"
                }    
            }
           /*post{
                success { 
                    mail to: "alaabouassida97@gmail.com",
                    subject: "Jenkins Stage : Deploy to Docker Hub is Success",
                    body: "Deploy to Docker Hub is Success"
                    echo 'success'
                }
                failure { 
                    mail to: "alaabouassida97@gmail.com",
                    subject: "Jenkins Stage : Deploy to Docker Hub is Success",
                    body: "Deploy to Docker Hub is Success"
                    echo 'failed'
                }
            }*/
        }
        /*stage('Deploy') {
            steps {
                script {
                    echo "Deploying..."
                    bat "kubectl apply -f kubernetes.yaml"
                }
            }
        }*/
    }
    post {
        always {
            echo "Cleaning up..."
            bat "cd ParkingDashboard && docker rmi -f parkingdashboard"
            bat "cd ParkingDashboard && docker rmi -f easyway07/parkingdashboard:latest"
            bat "docker logout"
        }
    }
}